### ISSUE TITLE
Broken bfs_search 

### ISSUE THREAD

**Issue by d-qn** [lgnbhl/BFS#1]
Hello,

great idea with this package! However I just gave it a try and it seems BFS changed the location of their list of cubes. I get an error when using it:

`bfs_search("student", langage = "en") `

It seems that the [URL](https://www.pxweb.bfs.admin.ch/ShowCubeList.aspx?px_language=de) it is trying to fetch the list of cubes no longer exists. I have briefly tried to find a new URL for it, but instead I only found this (lame) [webpage](https://www.bfs.admin.ch/bfs/fr/home/statistiques/catalogues-banques-donnees/donnees.html?dyn_pageIndex=0) instead of a proper spreadsheet.

**Comment by lgnbhl** [comment]
Hello Duc-Quang,

Thank you for your message and your interest in my package. And sorry for my late answer.

I finally took the time to rebuild the package based on the webpage link you shared in your comment. Indeed the list of cubes no longer exists. 

The `bfs_search()` function should now work. 

Please let me know if it works for you. 

I hope you will find this package useful.

Best,
Félix

**Comment by d-qn** [comment]
Hi Félix,

Yes, it is working now, cheers!
