### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Rengervn** [lgnbhl/BFS#11]
Hi Felix

Unfortunately, the package is not installable using R 4.0.4 and I think it is because of the new pipe symbol you are using.
If this is the case, you should change the line in your description file "Depends: R (>= 3.0.1)" to "Depends: R (>= 4.1).
But perhaps the error is because of other stuff.

Here is my error:
```
Error in parse(outFile) : 
  C:/Users/U80857517/AppData/Local/Temp/RtmpghOsTR/R.INSTALL35782e553008/BFS/R/bfs_get_asset_metadata.R:29:100: unexpected '>'
28:   
29:   asset_metadata <- httr2::request(base_url = "https://dam-api.bfs.admin.ch/hub/api/dam/assets/") |>
                                                                                                       ^
ERROR: unable to collate and parse R files for package 'BFS'
* removing 'C:/Program Files/R/R-4.0.4/library/BFS'
Warning in install.packages :
  installation of package ‘BFS’ had non-zero exit status
```
This means that we at the BFS can't install it as we are still working with 4.0.4. Or I just clone it (on my private computer as this is also not allowed at the BFS) and replace all ">" by "%>%". Transfer it to my office computer and install it.

Cheers
Renger

**Comment by lgnbhl** [comment]
Hi Ranger,

Thank you so much for posting this issue. I updated all the new pipe with the magrittr "%>%" pipe in the new version (0.5.4) of the BFS package on GitHub, so you can use it at the BFS. Thanks for letting me know about it.

The updated package is on GitHub and should be on CRAN very soon.

Please let me know if this fix your issue.

Cheers,
Felix

**Comment by Rengervn** [comment]
Hallo Felix

Ich habe die Github-Zip-Datei hinuntergeladen (wir können nicht direkt von Github installieren 🙁) und das Package kompiliert und installiert. Es funktioniert jetzt wunderbar.
Danke für die gute Arbeit!
Liebe Grüsse
Renger

________________________________
Von: Félix Luginbuhl ***@***.***>
Gesendet: Mittwoch, 13. September 2023 10:09
An: lgnbhl/BFS ***@***.***>
Cc: Renger van Nieuwkoop ***@***.***>; Author ***@***.***>
Betreff: Re: [lgnbhl/BFS] Error when installing (Issue #11)


Hi Ranger,

Thank you so much for posting this issue. I updated all the new pipe with the magrittr "%>%" pipe in the new version (0.5.4) of the BFS package on GitHub, so you can use it at the BFS. Thanks for letting me know about it.

The updated package is on GitHub and should be on CRAN very soon.

Please let me know if this fix your issue.

Cheers,
Felix

**Comment by lgnbhl** [comment]
Hallo Renger,
Great! This new version of the BFS R package will hit CRAN very soon :)
Liebe Grüsse,
Félix
